<?php

namespace webd\vectors;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-08 at 11:27:09.
 */
class MatrixTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Matrix
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Matrix(array(
            array(1, 2, 3),
            array(4, 5, 6),
            array(1, 6, 5)
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\vectors\Matrix::eigenvalue
     * @todo   Implement testEigenvalue().
     */
    public function testEigenvalue() {
        $this->assertEquals(
                12.1133,
                $this->object->eigenvalue(),
                "",
                0.0001);
    }

    /**
     * @covers webd\vectors\Matrix::eigenvector
     * @todo   Implement testEigenvector().
     */
    public function testEigenvector() {
        $this->assertEquals(
                array(0.3, 0.708, 0.6393),
                $this->object->eigenvector()->getValue(),
                "",
                0.0001);
    }

    /**
     * @covers webd\vectors\Matrix::cov
     * @todo   Implement testCov().
     */
    public function testCov() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Matrix::dotProduct
     * @todo   Implement testDotProduct().
     */
    public function testDotProduct() {
        $v = new Vector (1,2,3);
        $this->assertEquals(
                array(14,32,28),
                $this->object->dotProduct($v)->getValue());
    }

    /**
     * @covers webd\vectors\Matrix::__concat
     * @todo   Implement test__concat().
     */
    public function test__concat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
