<?php

namespace webd\vectors;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-07 at 16:39:52.
 */
class VectorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Vector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Vector(1,2,3);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\vectors\Vector::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        $this->assertEquals(array(1,2,3), $this->object->getValue());

    }

    /**
     * @covers webd\vectors\Vector::display
     * @todo   Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $v = new Vector(4,5,6);
        $r = $this->object->add($v);
        $this->assertInstanceOf('\webd\vectors\Vector', $r);
        
        $this->assertEquals(array(2.1,3.1,4.1), $this->object->add(1.1)->getValue());

    }

    /**
     * @covers webd\vectors\Vector::sub
     * @todo   Implement testSub().
     */
    public function testSub() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::dotProduct
     * @todo   Implement testDotProduct().
     */
    public function testDotProduct() {
        $this->assertEquals(14, $this->object->dotProduct($this->object));
    }

    /**
     * @covers webd\vectors\Vector::crossProduct
     * @todo   Implement testCrossProduct().
     */
    public function testCrossProduct() {
        $other = new Vector(4,5,6);
        $r = $this->object->crossProduct($other);
        $this->assertEquals(array(-3,6,-3), $r->getValue());
    }

    /**
     * @covers webd\vectors\Vector::div
     * @todo   Implement testDiv().
     */
    public function testDiv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::__add
     * @todo   Implement test__add().
     */
    public function test__add() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::__sub
     * @todo   Implement test__sub().
     */
    public function test__sub() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::__concat
     * @todo   Implement test__concat().
     */
    public function test__concat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::__mul
     * @todo   Implement test__mul().
     */
    public function test__mul() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::__div
     * @todo   Implement test__div().
     */
    public function test__div() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::mean
     * @todo   Implement testMean().
     */
    public function testMean() {
        $this->assertEquals(2, $this->object->mean());
    }

    /**
     * @covers webd\vectors\Vector::variance
     * @todo   Implement testVariance().
     */
    public function testVariance() {
        $this->assertEquals(1, $this->object->variance());
    }

    /**
     * @covers webd\vectors\Vector::standardDeviation
     * @todo   Implement testStandardDeviation().
     */
    public function testStandardDeviation() {
        $this->assertEquals(1, $this->object->standardDeviation());
    }

    /**
     * @covers webd\vectors\Vector::standardNormal
     * @todo   Implement testStandardNormal().
     */
    public function testStandardNormal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::sort
     * @todo   Implement testSort().
     */
    public function testSort() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::ecdf
     * @todo   Implement testEcdf().
     */
    public function testEcdf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::adtest
     * @todo   Implement testAdtest().
     */
    public function testAdtest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::isGaussian
     * @todo   Implement testIsGaussian().
     */
    public function testIsGaussian() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\vectors\Vector::normalize
     * @todo   Implement testNormalize().
     */
    public function testNormalize() {
        $this->assertEquals(1, $this->object->normalize()->norm());
    }

    /**
     * @covers webd\vectors\Vector::norm
     * @todo   Implement testNorm().
     */
    public function testNorm() {
        $this->assertEquals(3.7417, $this->object->norm(), '', 0.0001);
    }

    /**
     * @covers webd\vectors\Vector::length
     * @todo   Implement testLength().
     */
    public function testLength() {
        $this->assertEquals(3, $this->object->length());
    }

    /**
     * @covers webd\vectors\Vector::scalarProject
     * @todo   Implement testScalarProject().
     */
    public function testScalarProject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
